name: Build and test ppx_defer

on:
  - push
  - pull_request

jobs:
  build:
    name: Build and test

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.14.x
          - 4.11.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          dune-cache: ${{ matrix.os != 'macos-latest' }}
          opam-depext: true
          opam-depext-flags: --with-test
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune runtest
